name: "Clean up registry"

on:
  delete:
  workflow_dispatch:

jobs:
  delete_images:
    name: "Delete ghcr.io images ${{ github.event.ref }}"
    runs-on: ubuntu-latest
    environment: Registry
    steps:
      - uses: NethServer/ns8-github-actions/.github/actions/delete-image@v1
        with:
          images: "kickstart"
          delete_image_token: ${{ secrets.IMAGES_CLEANUP_TOKEN }}
